### ISSUE TITLE
CGO error gcc not found

### ISSUE THREAD

**Issue by CameronGo** [blang/golang-alpine-docker#2]
I only recently started attempting to use alpine and I'm attempting to get my Go code to compiled for that environment.  In this project I'm using CGO and my go build command outputs this error:
```
# runtime/cgo
exec: "gcc": executable file not found in $PATH
```
Am I not able to build a project using CGO on this image?  Or am I missing a step/requirement to be able to do so?

**Comment by blang** [comment]
Yes, CGO is not supported. You can use the official golang docker images which are now also based on alpine

https://github.com/docker-library/golang/blob/master/1.7/alpine3.5/Dockerfile

**Comment by CameronGo** [comment]
OK - thanks.  That's what I'm using now and I have that one working.
